workflows:
  ios-capacitor-workflow:
    name: Aslam AI Menu iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios_configs # 1. ADDED: This connects to your variables in the UI
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web Project
        script: |
          npm run build
          ls -R dist
      - name: Generate export_options.plist
        script: |
          # 2. ADDED: This recreates the file from your base64 variable
          echo $EXPORT_OPTIONS_PLIST | base64 --decode > ios/App/export_options.plist
      - name: Capacitor Sync
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Build iOS Project
        script: |
          # 3. UPDATED: Added the --export-options-plist flag
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --export-options-plist "ios/App/export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
